過去問2020 せんべい 難易度3 「5ベキ」
vvani06/pg_batttle_2023_shojin pull request #13
Opened 2023-10-12 14:31 UTC by yoto1980yen

## 解いた問題

過去問2020 せんべい 難易度3 「5ベキ」
https://products.sint.co.jp/hubfs/resource/topsic/pgb2020/2_2.pdf

## 問題の解釈

以前もやったことがある正確な小数を出力する問題

## 実装方針

この記事から正確な小数が得られそうなのでそのままコピっちゃいました
https://qiita.com/jkr_2255/items/0321b411243daf549ffc

提出例よりもより正確な値を出してしまったので「あれぼくなんかやっちゃいましたか？」って言う異世界系無自覚最強主人公になってます
果たしてこれでACになるかわからないです。

## 想定する計算量

O(1)

2023-10-12 14:41 UTC, vvani06 requested changes
> 提出例よりもより正確な値を出してしまったので「あれぼくなんかやっちゃいましたか？」って言う異世界系無自覚最強主人公になってます
果たしてこれでACになるかわからないです。

桁数が多いほど正確な値とは限らない！
この問題の題意からすると、サンプルの出力と「完全一致」しないと WA になると思います！

2023-10-12 14:45 UTC, yoto1980yen commented
> 桁数が多いほど正確な値とは限らない！ この問題の題意からすると、サンプルの出力と「完全一致」しないとWAになると思います！
ですよね
いい感じに提出例通りに出来ないかもう少し探してみます

2023-10-12 15:08 UTC, yoto1980yen commented
@vvani06 
bigdecimalを使ったら普通に想定解通りでした。
確認お願いします
前解いたAtCoderの問題に引っ張られてもっと正確にしなければって思ってましたね

2023-10-12 23:10 UTC, vvani06 approved these changes
よさそう！
D言語でこの問題でたらつらいな…(rationalも実数に対応したbigdecimalもないため)

2023-10-15 12:58 UTC, daylight55 approved these changes
LGTMです！
`bigdecimal`自分もちゃんと意識しておきます。。。(流石にスニペット作らないとまずいですね)

2023-10-15 13:01 UTC, yoto1980yen commented
こう見るとrubyは正確な小数の問題に強そうですよね。便利なライブラリがたくさん！
LGTMいただいたのでマージします！

2023-10-15 13:01 UTC, merged